# Generated by Django 5.0.1 on 2025-04-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0017_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='recommendedtest',
            field=models.TextField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='remark',
            field=models.CharField(default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_of_appointment',
            field=models.TimeField(),
        ),
    ]
