# Generated by Django 5.0.1 on 2026-05-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0018_alter_appointment_date_of_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mobilenumber',
            field=models.CharField(max_length=10),
        ),
    ]
