# Generated by Django 5.0.1 on 2026-05-01 11:54

import dasapp.models
import django.core.validators
from django.db import migrations, models
from datetime import datetime, timedelta
import random


def normalize_phone(value):
    value = str(value or '').strip().replace(' ', '').replace('-', '')
    if not value or value == '0':
        return ''
    if value.startswith('+'):
        return value[:16]
    if value.startswith('0'):
        return f'+254{value[1:]}'[:16]
    return f'+254{value}'[:16]


def next_unique_number(used_numbers):
    while True:
        number = random.randint(100000000, 999999999)
        if number not in used_numbers:
            used_numbers.add(number)
            return number


def prepare_existing_data(apps, schema_editor):
    Appointment = apps.get_model('dasapp', 'Appointment')
    DoctorReg = apps.get_model('dasapp', 'DoctorReg')
    Page = apps.get_model('dasapp', 'Page')

    used_numbers = set()
    occupied_slots = set()

    for appointment in Appointment.objects.order_by('id'):
        if not appointment.appointmentnumber or appointment.appointmentnumber in used_numbers:
            appointment.appointmentnumber = next_unique_number(used_numbers)
        else:
            used_numbers.add(appointment.appointmentnumber)

        appointment.mobilenumber = normalize_phone(appointment.mobilenumber)
        if appointment.status in ('1', 1):
            appointment.status = 'Approved'
        elif appointment.status in ('2', 2):
            appointment.status = 'Cancelled'
        elif appointment.status in ('3', 3):
            appointment.status = 'Completed'
        elif appointment.status not in ('0', 'Approved', 'Cancelled', 'Completed'):
            appointment.status = '0'
        if appointment.prescription == '0':
            appointment.prescription = ''
        if appointment.recommendedtest == '0':
            appointment.recommendedtest = ''

        slot = (
            appointment.doctor_id_id,
            appointment.date_of_appointment,
            appointment.time_of_appointment,
        )
        while slot in occupied_slots:
            appointment_datetime = datetime.combine(
                appointment.date_of_appointment,
                appointment.time_of_appointment,
            ) + timedelta(minutes=1)
            appointment.time_of_appointment = appointment_datetime.time()
            slot = (
                appointment.doctor_id_id,
                appointment.date_of_appointment,
                appointment.time_of_appointment,
            )
        occupied_slots.add(slot)

        appointment.save(update_fields=[
            'appointmentnumber',
            'mobilenumber',
            'status',
            'prescription',
            'recommendedtest',
            'time_of_appointment',
        ])

    for doctor in DoctorReg.objects.all():
        doctor.mobilenumber = normalize_phone(doctor.mobilenumber)
        doctor.save(update_fields=['mobilenumber'])

    for page in Page.objects.all():
        page.mobilenumber = normalize_phone(page.mobilenumber)
        page.save(update_fields=['mobilenumber'])


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0019_alter_appointment_mobilenumber'),
    ]

    operations = [
        migrations.RunPython(prepare_existing_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentnumber',
            field=models.PositiveIntegerField(db_index=True, default=dasapp.models.generate_appointment_number, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='mobilenumber',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must use E.164 format, for example +254712345678.', regex='^\\+[1-9]\\d{1,14}$')]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='recommendedtest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('0', 'New'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'doc'), ('3', 'patient')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='mobilenumber',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must use E.164 format, for example +254712345678.', regex='^\\+[1-9]\\d{1,14}$')]),
        ),
        migrations.AlterField(
            model_name='page',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must use E.164 format, for example +254712345678.', regex='^\\+[1-9]\\d{1,14}$')]),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor_id', 'date_of_appointment', 'time_of_appointment'), name='unique_doctor_appointment_slot'),
        ),
    ]
